
steps:
  - label: ":construction_worker: Make shared test env"
    command: buildkite/make-test-env.sh

  - wait

  - label: ":mag: Test back-end"
    command: buildkite/test-back-end.sh

  - label: ":mag: Test front-end"
    command: buildkite/test-front-end.sh

  - label: ":mag: Test in browser"
    command: buildkite/test-e2e.sh

  - wait

  - label: ":construction_worker: Push app image"
    command: buildkite/push-app-image.sh
